[build]
  command = "python app.py"  # Adjust this based on your actual build command
  command = "gunicorn -b :$PORT app:app"

  publish = "app.py"              # Adjust this based on your actual publish directory

  

